import Header from '@/components/Layout/Header';
import Footer from '@/components/Layout/Footer';

import './globals.css';

export const metadata = {
  title: 'TelleNet Pro',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel="icon" href="/icon.png" />
      </head>
      <body className='bg-bgColor text-textColor'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
